#!/bin/sh
case "$1" in
  start)
	printf "Starting mdev"
	echo /sbin/mdev > /proc/sys/kernel/hotplug
	/sbin/mdev -s
	;;
  stop)
	printf "Stopping mdev"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
exit $?
